apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: aks-store
  labels:
    app: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: ghcr.io/markjeffridelacruz/aks-store-devops/ai-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: USE_AZURE_OPENAI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USE_AZURE_OPENAI
            - name: AZURE_OPENAI_DEPLOYMENT_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AZURE_OPENAI_DEPLOYMENT_NAME
            - name: AZURE_OPENAI_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AZURE_OPENAI_ENDPOINT
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY
            - name: OPENAI_ORG_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_ORG_ID
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
