apiVersion: v1
kind: Service
metadata:
  name: store-admin
  namespace: aks-store
  labels:
    app: store-admin
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: store-admin
